plugins {
    id 'java'
}

group = 'com.espboorg'
version = '0.0.1-SNAPSHOT'
description = 'JavaTasks'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform("org.junit:junit-bom:6.1.3")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.named('test') {
    useJUnitPlatform()
}
